// Generated by gencpp from file control_planner_interface/VehicleExecuteGoal.msg
// DO NOT EDIT!


#ifndef CONTROL_PLANNER_INTERFACE_MESSAGE_VEHICLEEXECUTEGOAL_H
#define CONTROL_PLANNER_INTERFACE_MESSAGE_VEHICLEEXECUTEGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <control_planner_interface/Path.h>

namespace control_planner_interface
{
template <class ContainerAllocator>
struct VehicleExecuteGoal_
{
  typedef VehicleExecuteGoal_<ContainerAllocator> Type;

  VehicleExecuteGoal_()
    : header()
    , paths()  {
    }
  VehicleExecuteGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , paths(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::control_planner_interface::Path_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::control_planner_interface::Path_<ContainerAllocator> >> _paths_type;
  _paths_type paths;





  typedef boost::shared_ptr< ::control_planner_interface::VehicleExecuteGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_planner_interface::VehicleExecuteGoal_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleExecuteGoal_

typedef ::control_planner_interface::VehicleExecuteGoal_<std::allocator<void> > VehicleExecuteGoal;

typedef boost::shared_ptr< ::control_planner_interface::VehicleExecuteGoal > VehicleExecuteGoalPtr;
typedef boost::shared_ptr< ::control_planner_interface::VehicleExecuteGoal const> VehicleExecuteGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_planner_interface::VehicleExecuteGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_planner_interface::VehicleExecuteGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::control_planner_interface::VehicleExecuteGoal_<ContainerAllocator1> & lhs, const ::control_planner_interface::VehicleExecuteGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.paths == rhs.paths;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::control_planner_interface::VehicleExecuteGoal_<ContainerAllocator1> & lhs, const ::control_planner_interface::VehicleExecuteGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace control_planner_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::control_planner_interface::VehicleExecuteGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_planner_interface::VehicleExecuteGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_planner_interface::VehicleExecuteGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_planner_interface::VehicleExecuteGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_planner_interface::VehicleExecuteGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_planner_interface::VehicleExecuteGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_planner_interface::VehicleExecuteGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e21e8c5e28e6d789ac78508e9508ea07";
  }

  static const char* value(const ::control_planner_interface::VehicleExecuteGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe21e8c5e28e6d789ULL;
  static const uint64_t static_value2 = 0xac78508e9508ea07ULL;
};

template<class ContainerAllocator>
struct DataType< ::control_planner_interface::VehicleExecuteGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_planner_interface/VehicleExecuteGoal";
  }

  static const char* value(const ::control_planner_interface::VehicleExecuteGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_planner_interface::VehicleExecuteGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"std_msgs/Header  header\n"
"Path[] paths\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: control_planner_interface/Path\n"
"geometry_msgs/Pose[] path\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::control_planner_interface::VehicleExecuteGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_planner_interface::VehicleExecuteGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.paths);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleExecuteGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_planner_interface::VehicleExecuteGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_planner_interface::VehicleExecuteGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "paths[]" << std::endl;
    for (size_t i = 0; i < v.paths.size(); ++i)
    {
      s << indent << "  paths[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::control_planner_interface::Path_<ContainerAllocator> >::stream(s, indent + "    ", v.paths[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_PLANNER_INTERFACE_MESSAGE_VEHICLEEXECUTEGOAL_H
