# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from planner/EdgePair.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import planner.msg

class EdgePair(genpy.Message):
  _md5sum = "a7f192530926af30a2bd0e4f00396d0a"
  _type = "planner/EdgePair"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
int32 edge_id
IdPointPair begin_point
IdPointPair end_point
================================================================================
MSG: planner/IdPointPair
int32 id
geometry_msgs/Point point
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['edge_id','begin_point','end_point']
  _slot_types = ['int32','planner/IdPointPair','planner/IdPointPair']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       edge_id,begin_point,end_point

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EdgePair, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.edge_id is None:
        self.edge_id = 0
      if self.begin_point is None:
        self.begin_point = planner.msg.IdPointPair()
      if self.end_point is None:
        self.end_point = planner.msg.IdPointPair()
    else:
      self.edge_id = 0
      self.begin_point = planner.msg.IdPointPair()
      self.end_point = planner.msg.IdPointPair()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2i3di3d().pack(_x.edge_id, _x.begin_point.id, _x.begin_point.point.x, _x.begin_point.point.y, _x.begin_point.point.z, _x.end_point.id, _x.end_point.point.x, _x.end_point.point.y, _x.end_point.point.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.begin_point is None:
        self.begin_point = planner.msg.IdPointPair()
      if self.end_point is None:
        self.end_point = planner.msg.IdPointPair()
      end = 0
      _x = self
      start = end
      end += 60
      (_x.edge_id, _x.begin_point.id, _x.begin_point.point.x, _x.begin_point.point.y, _x.begin_point.point.z, _x.end_point.id, _x.end_point.point.x, _x.end_point.point.y, _x.end_point.point.z,) = _get_struct_2i3di3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2i3di3d().pack(_x.edge_id, _x.begin_point.id, _x.begin_point.point.x, _x.begin_point.point.y, _x.begin_point.point.z, _x.end_point.id, _x.end_point.point.x, _x.end_point.point.y, _x.end_point.point.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.begin_point is None:
        self.begin_point = planner.msg.IdPointPair()
      if self.end_point is None:
        self.end_point = planner.msg.IdPointPair()
      end = 0
      _x = self
      start = end
      end += 60
      (_x.edge_id, _x.begin_point.id, _x.begin_point.point.x, _x.begin_point.point.y, _x.begin_point.point.z, _x.end_point.id, _x.end_point.point.x, _x.end_point.point.y, _x.end_point.point.z,) = _get_struct_2i3di3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i3di3d = None
def _get_struct_2i3di3d():
    global _struct_2i3di3d
    if _struct_2i3di3d is None:
        _struct_2i3di3d = struct.Struct("<2i3di3d")
    return _struct_2i3di3d
