# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from planner/PreprocessMsgs.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import planner.msg
import std_msgs.msg
import ufomap_manager.msg
import ufomap_msgs.msg

class PreprocessMsgs(genpy.Message):
  _md5sum = "73bcf5cb2848fb40ea7e49ae1282eac0"
  _type = "planner/PreprocessMsgs"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """
Header header

ufomap_manager/UfomapWithFrontiers ufomap_with_frontiers

ViewpointsWithFrontiers[] viewpoint_frontiers_set

RoadMapMsg road_map_msg

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: ufomap_manager/UfomapWithFrontiers
Header header

ufomap_msgs/UFOMap  ufomap

#geometry_msgs/Point[] local_frontiers_center
#geometry_msgs/Point[] global_frontiers_center
#
#int32 frontiers_depth

ufomap_manager/CellCode[] local_frontiers
ufomap_manager/CellCode[] global_frontiers
ufomap_manager/CellCode[] changed_cell_codes
ufomap_manager/CellCode[] known_cell_codes

# 构建ufomap时机器人的参数配置
string frame_id
string robot_base_frame_id
float64 robot_height
float64 robot_bottom
float64 robot_radius
float64 max_range

uint32 known_plane_cell_num
================================================================================
MSG: ufomap_msgs/UFOMap
# A 3D map in binary format, as Octree
ufomap_msgs/UFOMapMetaData info

# Binary serialization of Octree, use conversions.h to read and write octrees
int8[] data
================================================================================
MSG: ufomap_msgs/UFOMapMetaData
# File version used
string version

# Class id of the contained Octree
string id

# Resolution (in m) of the octree leaf nodes
float64 resolution

# Number of depth levels
uint8 depth_levels

# If data is compressed
bool compressed

# Size of data uncompressed
int32 uncompressed_data_size

# Bounding volume
ufomap_msgs/BoundingVolume bounding_volume
================================================================================
MSG: ufomap_msgs/BoundingVolume
ufomap_msgs/AABB[] aabbs

# ufomap_msgs/Capsule[] capsules

# ufomap_msgs/Cone[] cones

# ufomap_msgs/Cylinder[] cylinders

# ufomap_msgs/Ellipsoid[] ellipsoids

ufomap_msgs/Frustum[] frustums

ufomap_msgs/LineSegment[] line_segments

ufomap_msgs/OBB[] obbs

ufomap_msgs/Plane[] planes

ufomap_msgs/Point[] points

ufomap_msgs/Ray[] rays

ufomap_msgs/Sphere[] spheres

# ufomap_msgs/Triangle[] triangles
================================================================================
MSG: ufomap_msgs/AABB
ufomap_msgs/Point center

ufomap_msgs/Point half_size
================================================================================
MSG: ufomap_msgs/Point
float64 x
float64 y
float64 z
================================================================================
MSG: ufomap_msgs/Frustum
ufomap_msgs/Plane[6] planes
================================================================================
MSG: ufomap_msgs/Plane
ufomap_msgs/Point normal

float64 distance
================================================================================
MSG: ufomap_msgs/LineSegment
ufomap_msgs/Point start

ufomap_msgs/Point end
================================================================================
MSG: ufomap_msgs/OBB
ufomap_msgs/Point center

ufomap_msgs/Point half_size

ufomap_msgs/Point rotation
================================================================================
MSG: ufomap_msgs/Ray
ufomap_msgs/Point origin

ufomap_msgs/Point direction
================================================================================
MSG: ufomap_msgs/Sphere
ufomap_msgs/Point center

float64 radius
================================================================================
MSG: ufomap_manager/CellCode
uint32 depth
uint64 Code

================================================================================
MSG: planner/ViewpointsWithFrontiers

geometry_msgs/Point view_point
ufomap_manager/CellCode[] frontiers
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: planner/RoadMapMsg

IdPointPair[] id_point_pair_list
EdgePair[] edge_pair_list
================================================================================
MSG: planner/IdPointPair
int32 id
geometry_msgs/Point point
================================================================================
MSG: planner/EdgePair

int32 edge_id
IdPointPair begin_point
IdPointPair end_point"""
  __slots__ = ['header','ufomap_with_frontiers','viewpoint_frontiers_set','road_map_msg']
  _slot_types = ['std_msgs/Header','ufomap_manager/UfomapWithFrontiers','planner/ViewpointsWithFrontiers[]','planner/RoadMapMsg']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,ufomap_with_frontiers,viewpoint_frontiers_set,road_map_msg

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PreprocessMsgs, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ufomap_with_frontiers is None:
        self.ufomap_with_frontiers = ufomap_manager.msg.UfomapWithFrontiers()
      if self.viewpoint_frontiers_set is None:
        self.viewpoint_frontiers_set = []
      if self.road_map_msg is None:
        self.road_map_msg = planner.msg.RoadMapMsg()
    else:
      self.header = std_msgs.msg.Header()
      self.ufomap_with_frontiers = ufomap_manager.msg.UfomapWithFrontiers()
      self.viewpoint_frontiers_set = []
      self.road_map_msg = planner.msg.RoadMapMsg()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.ufomap_with_frontiers.header.seq, _x.ufomap_with_frontiers.header.stamp.secs, _x.ufomap_with_frontiers.header.stamp.nsecs))
      _x = self.ufomap_with_frontiers.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.ufomap_with_frontiers.ufomap.info.version
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.ufomap_with_frontiers.ufomap.info.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_d2Bi().pack(_x.ufomap_with_frontiers.ufomap.info.resolution, _x.ufomap_with_frontiers.ufomap.info.depth_levels, _x.ufomap_with_frontiers.ufomap.info.compressed, _x.ufomap_with_frontiers.ufomap.info.uncompressed_data_size))
      length = len(self.ufomap_with_frontiers.ufomap.info.bounding_volume.aabbs)
      buff.write(_struct_I.pack(length))
      for val1 in self.ufomap_with_frontiers.ufomap.info.bounding_volume.aabbs:
        _v1 = val1.center
        _x = _v1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v2 = val1.half_size
        _x = _v2
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.ufomap_with_frontiers.ufomap.info.bounding_volume.frustums)
      buff.write(_struct_I.pack(length))
      for val1 in self.ufomap_with_frontiers.ufomap.info.bounding_volume.frustums:
        if len(val1.planes) != 6:
          self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (6, len(val1.planes), 'val1.planes')))
        for val2 in val1.planes:
          _v3 = val2.normal
          _x = _v3
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _x = val2.distance
          buff.write(_get_struct_d().pack(_x))
      length = len(self.ufomap_with_frontiers.ufomap.info.bounding_volume.line_segments)
      buff.write(_struct_I.pack(length))
      for val1 in self.ufomap_with_frontiers.ufomap.info.bounding_volume.line_segments:
        _v4 = val1.start
        _x = _v4
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v5 = val1.end
        _x = _v5
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.ufomap_with_frontiers.ufomap.info.bounding_volume.obbs)
      buff.write(_struct_I.pack(length))
      for val1 in self.ufomap_with_frontiers.ufomap.info.bounding_volume.obbs:
        _v6 = val1.center
        _x = _v6
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v7 = val1.half_size
        _x = _v7
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v8 = val1.rotation
        _x = _v8
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.ufomap_with_frontiers.ufomap.info.bounding_volume.planes)
      buff.write(_struct_I.pack(length))
      for val1 in self.ufomap_with_frontiers.ufomap.info.bounding_volume.planes:
        _v9 = val1.normal
        _x = _v9
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1.distance
        buff.write(_get_struct_d().pack(_x))
      length = len(self.ufomap_with_frontiers.ufomap.info.bounding_volume.points)
      buff.write(_struct_I.pack(length))
      for val1 in self.ufomap_with_frontiers.ufomap.info.bounding_volume.points:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.ufomap_with_frontiers.ufomap.info.bounding_volume.rays)
      buff.write(_struct_I.pack(length))
      for val1 in self.ufomap_with_frontiers.ufomap.info.bounding_volume.rays:
        _v10 = val1.origin
        _x = _v10
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v11 = val1.direction
        _x = _v11
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.ufomap_with_frontiers.ufomap.info.bounding_volume.spheres)
      buff.write(_struct_I.pack(length))
      for val1 in self.ufomap_with_frontiers.ufomap.info.bounding_volume.spheres:
        _v12 = val1.center
        _x = _v12
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1.radius
        buff.write(_get_struct_d().pack(_x))
      length = len(self.ufomap_with_frontiers.ufomap.data)
      buff.write(_struct_I.pack(length))
      pattern = '<%sb'%length
      buff.write(struct.Struct(pattern).pack(*self.ufomap_with_frontiers.ufomap.data))
      length = len(self.ufomap_with_frontiers.local_frontiers)
      buff.write(_struct_I.pack(length))
      for val1 in self.ufomap_with_frontiers.local_frontiers:
        _x = val1
        buff.write(_get_struct_IQ().pack(_x.depth, _x.Code))
      length = len(self.ufomap_with_frontiers.global_frontiers)
      buff.write(_struct_I.pack(length))
      for val1 in self.ufomap_with_frontiers.global_frontiers:
        _x = val1
        buff.write(_get_struct_IQ().pack(_x.depth, _x.Code))
      length = len(self.ufomap_with_frontiers.changed_cell_codes)
      buff.write(_struct_I.pack(length))
      for val1 in self.ufomap_with_frontiers.changed_cell_codes:
        _x = val1
        buff.write(_get_struct_IQ().pack(_x.depth, _x.Code))
      length = len(self.ufomap_with_frontiers.known_cell_codes)
      buff.write(_struct_I.pack(length))
      for val1 in self.ufomap_with_frontiers.known_cell_codes:
        _x = val1
        buff.write(_get_struct_IQ().pack(_x.depth, _x.Code))
      _x = self.ufomap_with_frontiers.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.ufomap_with_frontiers.robot_base_frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4dI().pack(_x.ufomap_with_frontiers.robot_height, _x.ufomap_with_frontiers.robot_bottom, _x.ufomap_with_frontiers.robot_radius, _x.ufomap_with_frontiers.max_range, _x.ufomap_with_frontiers.known_plane_cell_num))
      length = len(self.viewpoint_frontiers_set)
      buff.write(_struct_I.pack(length))
      for val1 in self.viewpoint_frontiers_set:
        _v13 = val1.view_point
        _x = _v13
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        length = len(val1.frontiers)
        buff.write(_struct_I.pack(length))
        for val2 in val1.frontiers:
          _x = val2
          buff.write(_get_struct_IQ().pack(_x.depth, _x.Code))
      length = len(self.road_map_msg.id_point_pair_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.road_map_msg.id_point_pair_list:
        _x = val1.id
        buff.write(_get_struct_i().pack(_x))
        _v14 = val1.point
        _x = _v14
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.road_map_msg.edge_pair_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.road_map_msg.edge_pair_list:
        _x = val1.edge_id
        buff.write(_get_struct_i().pack(_x))
        _v15 = val1.begin_point
        _x = _v15.id
        buff.write(_get_struct_i().pack(_x))
        _v16 = _v15.point
        _x = _v16
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v17 = val1.end_point
        _x = _v17.id
        buff.write(_get_struct_i().pack(_x))
        _v18 = _v17.point
        _x = _v18
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ufomap_with_frontiers is None:
        self.ufomap_with_frontiers = ufomap_manager.msg.UfomapWithFrontiers()
      if self.viewpoint_frontiers_set is None:
        self.viewpoint_frontiers_set = None
      if self.road_map_msg is None:
        self.road_map_msg = planner.msg.RoadMapMsg()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.ufomap_with_frontiers.header.seq, _x.ufomap_with_frontiers.header.stamp.secs, _x.ufomap_with_frontiers.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ufomap_with_frontiers.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.ufomap_with_frontiers.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ufomap_with_frontiers.ufomap.info.version = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.ufomap_with_frontiers.ufomap.info.version = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ufomap_with_frontiers.ufomap.info.id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.ufomap_with_frontiers.ufomap.info.id = str[start:end]
      _x = self
      start = end
      end += 14
      (_x.ufomap_with_frontiers.ufomap.info.resolution, _x.ufomap_with_frontiers.ufomap.info.depth_levels, _x.ufomap_with_frontiers.ufomap.info.compressed, _x.ufomap_with_frontiers.ufomap.info.uncompressed_data_size,) = _get_struct_d2Bi().unpack(str[start:end])
      self.ufomap_with_frontiers.ufomap.info.compressed = bool(self.ufomap_with_frontiers.ufomap.info.compressed)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ufomap_with_frontiers.ufomap.info.bounding_volume.aabbs = []
      for i in range(0, length):
        val1 = ufomap_msgs.msg.AABB()
        _v19 = val1.center
        _x = _v19
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v20 = val1.half_size
        _x = _v20
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.ufomap_with_frontiers.ufomap.info.bounding_volume.aabbs.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ufomap_with_frontiers.ufomap.info.bounding_volume.frustums = []
      for i in range(0, length):
        val1 = ufomap_msgs.msg.Frustum()
        val1.planes = []
        for i in range(0, 6):
          val2 = ufomap_msgs.msg.Plane()
          _v21 = val2.normal
          _x = _v21
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 8
          (val2.distance,) = _get_struct_d().unpack(str[start:end])
          val1.planes.append(val2)
        self.ufomap_with_frontiers.ufomap.info.bounding_volume.frustums.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ufomap_with_frontiers.ufomap.info.bounding_volume.line_segments = []
      for i in range(0, length):
        val1 = ufomap_msgs.msg.LineSegment()
        _v22 = val1.start
        _x = _v22
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v23 = val1.end
        _x = _v23
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.ufomap_with_frontiers.ufomap.info.bounding_volume.line_segments.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ufomap_with_frontiers.ufomap.info.bounding_volume.obbs = []
      for i in range(0, length):
        val1 = ufomap_msgs.msg.OBB()
        _v24 = val1.center
        _x = _v24
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v25 = val1.half_size
        _x = _v25
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v26 = val1.rotation
        _x = _v26
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.ufomap_with_frontiers.ufomap.info.bounding_volume.obbs.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ufomap_with_frontiers.ufomap.info.bounding_volume.planes = []
      for i in range(0, length):
        val1 = ufomap_msgs.msg.Plane()
        _v27 = val1.normal
        _x = _v27
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 8
        (val1.distance,) = _get_struct_d().unpack(str[start:end])
        self.ufomap_with_frontiers.ufomap.info.bounding_volume.planes.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ufomap_with_frontiers.ufomap.info.bounding_volume.points = []
      for i in range(0, length):
        val1 = ufomap_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.ufomap_with_frontiers.ufomap.info.bounding_volume.points.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ufomap_with_frontiers.ufomap.info.bounding_volume.rays = []
      for i in range(0, length):
        val1 = ufomap_msgs.msg.Ray()
        _v28 = val1.origin
        _x = _v28
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v29 = val1.direction
        _x = _v29
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.ufomap_with_frontiers.ufomap.info.bounding_volume.rays.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ufomap_with_frontiers.ufomap.info.bounding_volume.spheres = []
      for i in range(0, length):
        val1 = ufomap_msgs.msg.Sphere()
        _v30 = val1.center
        _x = _v30
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 8
        (val1.radius,) = _get_struct_d().unpack(str[start:end])
        self.ufomap_with_frontiers.ufomap.info.bounding_volume.spheres.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sb'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.ufomap_with_frontiers.ufomap.data = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ufomap_with_frontiers.local_frontiers = []
      for i in range(0, length):
        val1 = ufomap_manager.msg.CellCode()
        _x = val1
        start = end
        end += 12
        (_x.depth, _x.Code,) = _get_struct_IQ().unpack(str[start:end])
        self.ufomap_with_frontiers.local_frontiers.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ufomap_with_frontiers.global_frontiers = []
      for i in range(0, length):
        val1 = ufomap_manager.msg.CellCode()
        _x = val1
        start = end
        end += 12
        (_x.depth, _x.Code,) = _get_struct_IQ().unpack(str[start:end])
        self.ufomap_with_frontiers.global_frontiers.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ufomap_with_frontiers.changed_cell_codes = []
      for i in range(0, length):
        val1 = ufomap_manager.msg.CellCode()
        _x = val1
        start = end
        end += 12
        (_x.depth, _x.Code,) = _get_struct_IQ().unpack(str[start:end])
        self.ufomap_with_frontiers.changed_cell_codes.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ufomap_with_frontiers.known_cell_codes = []
      for i in range(0, length):
        val1 = ufomap_manager.msg.CellCode()
        _x = val1
        start = end
        end += 12
        (_x.depth, _x.Code,) = _get_struct_IQ().unpack(str[start:end])
        self.ufomap_with_frontiers.known_cell_codes.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ufomap_with_frontiers.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.ufomap_with_frontiers.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ufomap_with_frontiers.robot_base_frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.ufomap_with_frontiers.robot_base_frame_id = str[start:end]
      _x = self
      start = end
      end += 36
      (_x.ufomap_with_frontiers.robot_height, _x.ufomap_with_frontiers.robot_bottom, _x.ufomap_with_frontiers.robot_radius, _x.ufomap_with_frontiers.max_range, _x.ufomap_with_frontiers.known_plane_cell_num,) = _get_struct_4dI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.viewpoint_frontiers_set = []
      for i in range(0, length):
        val1 = planner.msg.ViewpointsWithFrontiers()
        _v31 = val1.view_point
        _x = _v31
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.frontiers = []
        for i in range(0, length):
          val2 = ufomap_manager.msg.CellCode()
          _x = val2
          start = end
          end += 12
          (_x.depth, _x.Code,) = _get_struct_IQ().unpack(str[start:end])
          val1.frontiers.append(val2)
        self.viewpoint_frontiers_set.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.road_map_msg.id_point_pair_list = []
      for i in range(0, length):
        val1 = planner.msg.IdPointPair()
        start = end
        end += 4
        (val1.id,) = _get_struct_i().unpack(str[start:end])
        _v32 = val1.point
        _x = _v32
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.road_map_msg.id_point_pair_list.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.road_map_msg.edge_pair_list = []
      for i in range(0, length):
        val1 = planner.msg.EdgePair()
        start = end
        end += 4
        (val1.edge_id,) = _get_struct_i().unpack(str[start:end])
        _v33 = val1.begin_point
        start = end
        end += 4
        (_v33.id,) = _get_struct_i().unpack(str[start:end])
        _v34 = _v33.point
        _x = _v34
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v35 = val1.end_point
        start = end
        end += 4
        (_v35.id,) = _get_struct_i().unpack(str[start:end])
        _v36 = _v35.point
        _x = _v36
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.road_map_msg.edge_pair_list.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.ufomap_with_frontiers.header.seq, _x.ufomap_with_frontiers.header.stamp.secs, _x.ufomap_with_frontiers.header.stamp.nsecs))
      _x = self.ufomap_with_frontiers.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.ufomap_with_frontiers.ufomap.info.version
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.ufomap_with_frontiers.ufomap.info.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_d2Bi().pack(_x.ufomap_with_frontiers.ufomap.info.resolution, _x.ufomap_with_frontiers.ufomap.info.depth_levels, _x.ufomap_with_frontiers.ufomap.info.compressed, _x.ufomap_with_frontiers.ufomap.info.uncompressed_data_size))
      length = len(self.ufomap_with_frontiers.ufomap.info.bounding_volume.aabbs)
      buff.write(_struct_I.pack(length))
      for val1 in self.ufomap_with_frontiers.ufomap.info.bounding_volume.aabbs:
        _v37 = val1.center
        _x = _v37
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v38 = val1.half_size
        _x = _v38
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.ufomap_with_frontiers.ufomap.info.bounding_volume.frustums)
      buff.write(_struct_I.pack(length))
      for val1 in self.ufomap_with_frontiers.ufomap.info.bounding_volume.frustums:
        if len(val1.planes) != 6:
          self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (6, len(val1.planes), 'val1.planes')))
        for val2 in val1.planes:
          _v39 = val2.normal
          _x = _v39
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _x = val2.distance
          buff.write(_get_struct_d().pack(_x))
      length = len(self.ufomap_with_frontiers.ufomap.info.bounding_volume.line_segments)
      buff.write(_struct_I.pack(length))
      for val1 in self.ufomap_with_frontiers.ufomap.info.bounding_volume.line_segments:
        _v40 = val1.start
        _x = _v40
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v41 = val1.end
        _x = _v41
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.ufomap_with_frontiers.ufomap.info.bounding_volume.obbs)
      buff.write(_struct_I.pack(length))
      for val1 in self.ufomap_with_frontiers.ufomap.info.bounding_volume.obbs:
        _v42 = val1.center
        _x = _v42
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v43 = val1.half_size
        _x = _v43
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v44 = val1.rotation
        _x = _v44
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.ufomap_with_frontiers.ufomap.info.bounding_volume.planes)
      buff.write(_struct_I.pack(length))
      for val1 in self.ufomap_with_frontiers.ufomap.info.bounding_volume.planes:
        _v45 = val1.normal
        _x = _v45
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1.distance
        buff.write(_get_struct_d().pack(_x))
      length = len(self.ufomap_with_frontiers.ufomap.info.bounding_volume.points)
      buff.write(_struct_I.pack(length))
      for val1 in self.ufomap_with_frontiers.ufomap.info.bounding_volume.points:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.ufomap_with_frontiers.ufomap.info.bounding_volume.rays)
      buff.write(_struct_I.pack(length))
      for val1 in self.ufomap_with_frontiers.ufomap.info.bounding_volume.rays:
        _v46 = val1.origin
        _x = _v46
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v47 = val1.direction
        _x = _v47
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.ufomap_with_frontiers.ufomap.info.bounding_volume.spheres)
      buff.write(_struct_I.pack(length))
      for val1 in self.ufomap_with_frontiers.ufomap.info.bounding_volume.spheres:
        _v48 = val1.center
        _x = _v48
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1.radius
        buff.write(_get_struct_d().pack(_x))
      length = len(self.ufomap_with_frontiers.ufomap.data)
      buff.write(_struct_I.pack(length))
      pattern = '<%sb'%length
      buff.write(self.ufomap_with_frontiers.ufomap.data.tostring())
      length = len(self.ufomap_with_frontiers.local_frontiers)
      buff.write(_struct_I.pack(length))
      for val1 in self.ufomap_with_frontiers.local_frontiers:
        _x = val1
        buff.write(_get_struct_IQ().pack(_x.depth, _x.Code))
      length = len(self.ufomap_with_frontiers.global_frontiers)
      buff.write(_struct_I.pack(length))
      for val1 in self.ufomap_with_frontiers.global_frontiers:
        _x = val1
        buff.write(_get_struct_IQ().pack(_x.depth, _x.Code))
      length = len(self.ufomap_with_frontiers.changed_cell_codes)
      buff.write(_struct_I.pack(length))
      for val1 in self.ufomap_with_frontiers.changed_cell_codes:
        _x = val1
        buff.write(_get_struct_IQ().pack(_x.depth, _x.Code))
      length = len(self.ufomap_with_frontiers.known_cell_codes)
      buff.write(_struct_I.pack(length))
      for val1 in self.ufomap_with_frontiers.known_cell_codes:
        _x = val1
        buff.write(_get_struct_IQ().pack(_x.depth, _x.Code))
      _x = self.ufomap_with_frontiers.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.ufomap_with_frontiers.robot_base_frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4dI().pack(_x.ufomap_with_frontiers.robot_height, _x.ufomap_with_frontiers.robot_bottom, _x.ufomap_with_frontiers.robot_radius, _x.ufomap_with_frontiers.max_range, _x.ufomap_with_frontiers.known_plane_cell_num))
      length = len(self.viewpoint_frontiers_set)
      buff.write(_struct_I.pack(length))
      for val1 in self.viewpoint_frontiers_set:
        _v49 = val1.view_point
        _x = _v49
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        length = len(val1.frontiers)
        buff.write(_struct_I.pack(length))
        for val2 in val1.frontiers:
          _x = val2
          buff.write(_get_struct_IQ().pack(_x.depth, _x.Code))
      length = len(self.road_map_msg.id_point_pair_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.road_map_msg.id_point_pair_list:
        _x = val1.id
        buff.write(_get_struct_i().pack(_x))
        _v50 = val1.point
        _x = _v50
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.road_map_msg.edge_pair_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.road_map_msg.edge_pair_list:
        _x = val1.edge_id
        buff.write(_get_struct_i().pack(_x))
        _v51 = val1.begin_point
        _x = _v51.id
        buff.write(_get_struct_i().pack(_x))
        _v52 = _v51.point
        _x = _v52
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v53 = val1.end_point
        _x = _v53.id
        buff.write(_get_struct_i().pack(_x))
        _v54 = _v53.point
        _x = _v54
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ufomap_with_frontiers is None:
        self.ufomap_with_frontiers = ufomap_manager.msg.UfomapWithFrontiers()
      if self.viewpoint_frontiers_set is None:
        self.viewpoint_frontiers_set = None
      if self.road_map_msg is None:
        self.road_map_msg = planner.msg.RoadMapMsg()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.ufomap_with_frontiers.header.seq, _x.ufomap_with_frontiers.header.stamp.secs, _x.ufomap_with_frontiers.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ufomap_with_frontiers.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.ufomap_with_frontiers.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ufomap_with_frontiers.ufomap.info.version = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.ufomap_with_frontiers.ufomap.info.version = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ufomap_with_frontiers.ufomap.info.id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.ufomap_with_frontiers.ufomap.info.id = str[start:end]
      _x = self
      start = end
      end += 14
      (_x.ufomap_with_frontiers.ufomap.info.resolution, _x.ufomap_with_frontiers.ufomap.info.depth_levels, _x.ufomap_with_frontiers.ufomap.info.compressed, _x.ufomap_with_frontiers.ufomap.info.uncompressed_data_size,) = _get_struct_d2Bi().unpack(str[start:end])
      self.ufomap_with_frontiers.ufomap.info.compressed = bool(self.ufomap_with_frontiers.ufomap.info.compressed)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ufomap_with_frontiers.ufomap.info.bounding_volume.aabbs = []
      for i in range(0, length):
        val1 = ufomap_msgs.msg.AABB()
        _v55 = val1.center
        _x = _v55
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v56 = val1.half_size
        _x = _v56
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.ufomap_with_frontiers.ufomap.info.bounding_volume.aabbs.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ufomap_with_frontiers.ufomap.info.bounding_volume.frustums = []
      for i in range(0, length):
        val1 = ufomap_msgs.msg.Frustum()
        val1.planes = []
        for i in range(0, 6):
          val2 = ufomap_msgs.msg.Plane()
          _v57 = val2.normal
          _x = _v57
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 8
          (val2.distance,) = _get_struct_d().unpack(str[start:end])
          val1.planes.append(val2)
        self.ufomap_with_frontiers.ufomap.info.bounding_volume.frustums.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ufomap_with_frontiers.ufomap.info.bounding_volume.line_segments = []
      for i in range(0, length):
        val1 = ufomap_msgs.msg.LineSegment()
        _v58 = val1.start
        _x = _v58
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v59 = val1.end
        _x = _v59
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.ufomap_with_frontiers.ufomap.info.bounding_volume.line_segments.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ufomap_with_frontiers.ufomap.info.bounding_volume.obbs = []
      for i in range(0, length):
        val1 = ufomap_msgs.msg.OBB()
        _v60 = val1.center
        _x = _v60
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v61 = val1.half_size
        _x = _v61
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v62 = val1.rotation
        _x = _v62
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.ufomap_with_frontiers.ufomap.info.bounding_volume.obbs.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ufomap_with_frontiers.ufomap.info.bounding_volume.planes = []
      for i in range(0, length):
        val1 = ufomap_msgs.msg.Plane()
        _v63 = val1.normal
        _x = _v63
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 8
        (val1.distance,) = _get_struct_d().unpack(str[start:end])
        self.ufomap_with_frontiers.ufomap.info.bounding_volume.planes.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ufomap_with_frontiers.ufomap.info.bounding_volume.points = []
      for i in range(0, length):
        val1 = ufomap_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.ufomap_with_frontiers.ufomap.info.bounding_volume.points.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ufomap_with_frontiers.ufomap.info.bounding_volume.rays = []
      for i in range(0, length):
        val1 = ufomap_msgs.msg.Ray()
        _v64 = val1.origin
        _x = _v64
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v65 = val1.direction
        _x = _v65
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.ufomap_with_frontiers.ufomap.info.bounding_volume.rays.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ufomap_with_frontiers.ufomap.info.bounding_volume.spheres = []
      for i in range(0, length):
        val1 = ufomap_msgs.msg.Sphere()
        _v66 = val1.center
        _x = _v66
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 8
        (val1.radius,) = _get_struct_d().unpack(str[start:end])
        self.ufomap_with_frontiers.ufomap.info.bounding_volume.spheres.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sb'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.ufomap_with_frontiers.ufomap.data = numpy.frombuffer(str[start:end], dtype=numpy.int8, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ufomap_with_frontiers.local_frontiers = []
      for i in range(0, length):
        val1 = ufomap_manager.msg.CellCode()
        _x = val1
        start = end
        end += 12
        (_x.depth, _x.Code,) = _get_struct_IQ().unpack(str[start:end])
        self.ufomap_with_frontiers.local_frontiers.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ufomap_with_frontiers.global_frontiers = []
      for i in range(0, length):
        val1 = ufomap_manager.msg.CellCode()
        _x = val1
        start = end
        end += 12
        (_x.depth, _x.Code,) = _get_struct_IQ().unpack(str[start:end])
        self.ufomap_with_frontiers.global_frontiers.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ufomap_with_frontiers.changed_cell_codes = []
      for i in range(0, length):
        val1 = ufomap_manager.msg.CellCode()
        _x = val1
        start = end
        end += 12
        (_x.depth, _x.Code,) = _get_struct_IQ().unpack(str[start:end])
        self.ufomap_with_frontiers.changed_cell_codes.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ufomap_with_frontiers.known_cell_codes = []
      for i in range(0, length):
        val1 = ufomap_manager.msg.CellCode()
        _x = val1
        start = end
        end += 12
        (_x.depth, _x.Code,) = _get_struct_IQ().unpack(str[start:end])
        self.ufomap_with_frontiers.known_cell_codes.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ufomap_with_frontiers.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.ufomap_with_frontiers.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ufomap_with_frontiers.robot_base_frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.ufomap_with_frontiers.robot_base_frame_id = str[start:end]
      _x = self
      start = end
      end += 36
      (_x.ufomap_with_frontiers.robot_height, _x.ufomap_with_frontiers.robot_bottom, _x.ufomap_with_frontiers.robot_radius, _x.ufomap_with_frontiers.max_range, _x.ufomap_with_frontiers.known_plane_cell_num,) = _get_struct_4dI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.viewpoint_frontiers_set = []
      for i in range(0, length):
        val1 = planner.msg.ViewpointsWithFrontiers()
        _v67 = val1.view_point
        _x = _v67
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.frontiers = []
        for i in range(0, length):
          val2 = ufomap_manager.msg.CellCode()
          _x = val2
          start = end
          end += 12
          (_x.depth, _x.Code,) = _get_struct_IQ().unpack(str[start:end])
          val1.frontiers.append(val2)
        self.viewpoint_frontiers_set.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.road_map_msg.id_point_pair_list = []
      for i in range(0, length):
        val1 = planner.msg.IdPointPair()
        start = end
        end += 4
        (val1.id,) = _get_struct_i().unpack(str[start:end])
        _v68 = val1.point
        _x = _v68
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.road_map_msg.id_point_pair_list.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.road_map_msg.edge_pair_list = []
      for i in range(0, length):
        val1 = planner.msg.EdgePair()
        start = end
        end += 4
        (val1.edge_id,) = _get_struct_i().unpack(str[start:end])
        _v69 = val1.begin_point
        start = end
        end += 4
        (_v69.id,) = _get_struct_i().unpack(str[start:end])
        _v70 = _v69.point
        _x = _v70
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v71 = val1.end_point
        start = end
        end += 4
        (_v71.id,) = _get_struct_i().unpack(str[start:end])
        _v72 = _v71.point
        _x = _v72
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.road_map_msg.edge_pair_list.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_4dI = None
def _get_struct_4dI():
    global _struct_4dI
    if _struct_4dI is None:
        _struct_4dI = struct.Struct("<4dI")
    return _struct_4dI
_struct_IQ = None
def _get_struct_IQ():
    global _struct_IQ
    if _struct_IQ is None:
        _struct_IQ = struct.Struct("<IQ")
    return _struct_IQ
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
_struct_d2Bi = None
def _get_struct_d2Bi():
    global _struct_d2Bi
    if _struct_d2Bi is None:
        _struct_d2Bi = struct.Struct("<d2Bi")
    return _struct_d2Bi
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
