(cl:defpackage planner-msg
  (:use )
  (:export
   "<EDGEPAIR>"
   "EDGEPAIR"
   "<IDPOINTPAIR>"
   "IDPOINTPAIR"
   "<PREPROCESSMSGS>"
   "PREPROCESSMSGS"
   "<ROADMAPMSG>"
   "ROADMAPMSG"
   "<VIEWPOINTSWITHFRONTIERS>"
   "VIEWPOINTSWITHFRONTIERS"
  ))

