// Auto-generated. Do not edit!

// (in-package control_planner_interface.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class ExplorerPlannerGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.iteration_id = null;
    }
    else {
      if (initObj.hasOwnProperty('iteration_id')) {
        this.iteration_id = initObj.iteration_id
      }
      else {
        this.iteration_id = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ExplorerPlannerGoal
    // Serialize message field [iteration_id]
    bufferOffset = _serializer.int32(obj.iteration_id, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ExplorerPlannerGoal
    let len;
    let data = new ExplorerPlannerGoal(null);
    // Deserialize message field [iteration_id]
    data.iteration_id = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'control_planner_interface/ExplorerPlannerGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '374377ab10495f5a9792cd599df80faf';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    int32 iteration_id
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ExplorerPlannerGoal(null);
    if (msg.iteration_id !== undefined) {
      resolved.iteration_id = msg.iteration_id;
    }
    else {
      resolved.iteration_id = 0
    }

    return resolved;
    }
};

module.exports = ExplorerPlannerGoal;
