; Auto-generated. Do not edit!


(cl:in-package control_planner_interface-msg)


;//! \htmlinclude ExplorerPlannerFeedback.msg.html

(cl:defclass <ExplorerPlannerFeedback> (roslisp-msg-protocol:ros-message)
  ((is_get_path
    :reader is_get_path
    :initarg :is_get_path
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass ExplorerPlannerFeedback (<ExplorerPlannerFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ExplorerPlannerFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ExplorerPlannerFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name control_planner_interface-msg:<ExplorerPlannerFeedback> is deprecated: use control_planner_interface-msg:ExplorerPlannerFeedback instead.")))

(cl:ensure-generic-function 'is_get_path-val :lambda-list '(m))
(cl:defmethod is_get_path-val ((m <ExplorerPlannerFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader control_planner_interface-msg:is_get_path-val is deprecated.  Use control_planner_interface-msg:is_get_path instead.")
  (is_get_path m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ExplorerPlannerFeedback>) ostream)
  "Serializes a message object of type '<ExplorerPlannerFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'is_get_path) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ExplorerPlannerFeedback>) istream)
  "Deserializes a message object of type '<ExplorerPlannerFeedback>"
    (cl:setf (cl:slot-value msg 'is_get_path) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ExplorerPlannerFeedback>)))
  "Returns string type for a message object of type '<ExplorerPlannerFeedback>"
  "control_planner_interface/ExplorerPlannerFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ExplorerPlannerFeedback)))
  "Returns string type for a message object of type 'ExplorerPlannerFeedback"
  "control_planner_interface/ExplorerPlannerFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ExplorerPlannerFeedback>)))
  "Returns md5sum for a message object of type '<ExplorerPlannerFeedback>"
  "26cf06fccc0ce6cdf56b8730dc1b64bc")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ExplorerPlannerFeedback)))
  "Returns md5sum for a message object of type 'ExplorerPlannerFeedback"
  "26cf06fccc0ce6cdf56b8730dc1b64bc")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ExplorerPlannerFeedback>)))
  "Returns full string definition for message of type '<ExplorerPlannerFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%bool is_get_path~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ExplorerPlannerFeedback)))
  "Returns full string definition for message of type 'ExplorerPlannerFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%bool is_get_path~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ExplorerPlannerFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ExplorerPlannerFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ExplorerPlannerFeedback
    (cl:cons ':is_get_path (is_get_path msg))
))
