; Auto-generated. Do not edit!


(cl:in-package control_planner_interface-msg)


;//! \htmlinclude ExplorerPlannerResult.msg.html

(cl:defclass <ExplorerPlannerResult> (roslisp-msg-protocol:ros-message)
  ((paths
    :reader paths
    :initarg :paths
    :type (cl:vector control_planner_interface-msg:Path)
   :initform (cl:make-array 0 :element-type 'control_planner_interface-msg:Path :initial-element (cl:make-instance 'control_planner_interface-msg:Path))))
)

(cl:defclass ExplorerPlannerResult (<ExplorerPlannerResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ExplorerPlannerResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ExplorerPlannerResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name control_planner_interface-msg:<ExplorerPlannerResult> is deprecated: use control_planner_interface-msg:ExplorerPlannerResult instead.")))

(cl:ensure-generic-function 'paths-val :lambda-list '(m))
(cl:defmethod paths-val ((m <ExplorerPlannerResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader control_planner_interface-msg:paths-val is deprecated.  Use control_planner_interface-msg:paths instead.")
  (paths m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ExplorerPlannerResult>) ostream)
  "Serializes a message object of type '<ExplorerPlannerResult>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'paths))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'paths))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ExplorerPlannerResult>) istream)
  "Deserializes a message object of type '<ExplorerPlannerResult>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'paths) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'paths)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'control_planner_interface-msg:Path))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ExplorerPlannerResult>)))
  "Returns string type for a message object of type '<ExplorerPlannerResult>"
  "control_planner_interface/ExplorerPlannerResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ExplorerPlannerResult)))
  "Returns string type for a message object of type 'ExplorerPlannerResult"
  "control_planner_interface/ExplorerPlannerResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ExplorerPlannerResult>)))
  "Returns md5sum for a message object of type '<ExplorerPlannerResult>"
  "e6096c7a4bd8897c92de88df9f0c3da7")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ExplorerPlannerResult)))
  "Returns md5sum for a message object of type 'ExplorerPlannerResult"
  "e6096c7a4bd8897c92de88df9f0c3da7")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ExplorerPlannerResult>)))
  "Returns full string definition for message of type '<ExplorerPlannerResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%Path[]  paths~%~%~%================================================================================~%MSG: control_planner_interface/Path~%geometry_msgs/Pose[] path~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ExplorerPlannerResult)))
  "Returns full string definition for message of type 'ExplorerPlannerResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%Path[]  paths~%~%~%================================================================================~%MSG: control_planner_interface/Path~%geometry_msgs/Pose[] path~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ExplorerPlannerResult>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'paths) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ExplorerPlannerResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ExplorerPlannerResult
    (cl:cons ':paths (paths msg))
))
