; Auto-generated. Do not edit!


(cl:in-package control_planner_interface-msg)


;//! \htmlinclude VehicleExecuteResult.msg.html

(cl:defclass <VehicleExecuteResult> (roslisp-msg-protocol:ros-message)
  ((finish
    :reader finish
    :initarg :finish
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass VehicleExecuteResult (<VehicleExecuteResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <VehicleExecuteResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'VehicleExecuteResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name control_planner_interface-msg:<VehicleExecuteResult> is deprecated: use control_planner_interface-msg:VehicleExecuteResult instead.")))

(cl:ensure-generic-function 'finish-val :lambda-list '(m))
(cl:defmethod finish-val ((m <VehicleExecuteResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader control_planner_interface-msg:finish-val is deprecated.  Use control_planner_interface-msg:finish instead.")
  (finish m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <VehicleExecuteResult>) ostream)
  "Serializes a message object of type '<VehicleExecuteResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'finish) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <VehicleExecuteResult>) istream)
  "Deserializes a message object of type '<VehicleExecuteResult>"
    (cl:setf (cl:slot-value msg 'finish) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<VehicleExecuteResult>)))
  "Returns string type for a message object of type '<VehicleExecuteResult>"
  "control_planner_interface/VehicleExecuteResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'VehicleExecuteResult)))
  "Returns string type for a message object of type 'VehicleExecuteResult"
  "control_planner_interface/VehicleExecuteResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<VehicleExecuteResult>)))
  "Returns md5sum for a message object of type '<VehicleExecuteResult>"
  "474a58dbb494a45bb1ca99544cd64e45")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'VehicleExecuteResult)))
  "Returns md5sum for a message object of type 'VehicleExecuteResult"
  "474a58dbb494a45bb1ca99544cd64e45")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<VehicleExecuteResult>)))
  "Returns full string definition for message of type '<VehicleExecuteResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool finish~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'VehicleExecuteResult)))
  "Returns full string definition for message of type 'VehicleExecuteResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool finish~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <VehicleExecuteResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <VehicleExecuteResult>))
  "Converts a ROS message object to a list"
  (cl:list 'VehicleExecuteResult
    (cl:cons ':finish (finish msg))
))
