# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from control_planner_interface/PlannerMsgs.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PlannerMsgs(genpy.Message):
  _md5sum = "8d4c2f6dbcc43449d62d74babfc48846"
  _type = "control_planner_interface/PlannerMsgs"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
int32 current_iteration_id
int32 current_goal_id   
bool is_current_goal_scanned
bool is_exploration_finished"""
  __slots__ = ['current_iteration_id','current_goal_id','is_current_goal_scanned','is_exploration_finished']
  _slot_types = ['int32','int32','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       current_iteration_id,current_goal_id,is_current_goal_scanned,is_exploration_finished

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PlannerMsgs, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.current_iteration_id is None:
        self.current_iteration_id = 0
      if self.current_goal_id is None:
        self.current_goal_id = 0
      if self.is_current_goal_scanned is None:
        self.is_current_goal_scanned = False
      if self.is_exploration_finished is None:
        self.is_exploration_finished = False
    else:
      self.current_iteration_id = 0
      self.current_goal_id = 0
      self.is_current_goal_scanned = False
      self.is_exploration_finished = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2i2B().pack(_x.current_iteration_id, _x.current_goal_id, _x.is_current_goal_scanned, _x.is_exploration_finished))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.current_iteration_id, _x.current_goal_id, _x.is_current_goal_scanned, _x.is_exploration_finished,) = _get_struct_2i2B().unpack(str[start:end])
      self.is_current_goal_scanned = bool(self.is_current_goal_scanned)
      self.is_exploration_finished = bool(self.is_exploration_finished)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2i2B().pack(_x.current_iteration_id, _x.current_goal_id, _x.is_current_goal_scanned, _x.is_exploration_finished))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.current_iteration_id, _x.current_goal_id, _x.is_current_goal_scanned, _x.is_exploration_finished,) = _get_struct_2i2B().unpack(str[start:end])
      self.is_current_goal_scanned = bool(self.is_current_goal_scanned)
      self.is_exploration_finished = bool(self.is_exploration_finished)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i2B = None
def _get_struct_2i2B():
    global _struct_2i2B
    if _struct_2i2B is None:
        _struct_2i2B = struct.Struct("<2i2B")
    return _struct_2i2B
