# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ufomap_msgs/OBB.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ufomap_msgs.msg

class OBB(genpy.Message):
  _md5sum = "e931b8e26c2b1c2b5808b3eacdf69e3d"
  _type = "ufomap_msgs/OBB"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """ufomap_msgs/Point center

ufomap_msgs/Point half_size

ufomap_msgs/Point rotation
================================================================================
MSG: ufomap_msgs/Point
float64 x
float64 y
float64 z"""
  __slots__ = ['center','half_size','rotation']
  _slot_types = ['ufomap_msgs/Point','ufomap_msgs/Point','ufomap_msgs/Point']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       center,half_size,rotation

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(OBB, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.center is None:
        self.center = ufomap_msgs.msg.Point()
      if self.half_size is None:
        self.half_size = ufomap_msgs.msg.Point()
      if self.rotation is None:
        self.rotation = ufomap_msgs.msg.Point()
    else:
      self.center = ufomap_msgs.msg.Point()
      self.half_size = ufomap_msgs.msg.Point()
      self.rotation = ufomap_msgs.msg.Point()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_9d().pack(_x.center.x, _x.center.y, _x.center.z, _x.half_size.x, _x.half_size.y, _x.half_size.z, _x.rotation.x, _x.rotation.y, _x.rotation.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.center is None:
        self.center = ufomap_msgs.msg.Point()
      if self.half_size is None:
        self.half_size = ufomap_msgs.msg.Point()
      if self.rotation is None:
        self.rotation = ufomap_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 72
      (_x.center.x, _x.center.y, _x.center.z, _x.half_size.x, _x.half_size.y, _x.half_size.z, _x.rotation.x, _x.rotation.y, _x.rotation.z,) = _get_struct_9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_9d().pack(_x.center.x, _x.center.y, _x.center.z, _x.half_size.x, _x.half_size.y, _x.half_size.z, _x.rotation.x, _x.rotation.y, _x.rotation.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.center is None:
        self.center = ufomap_msgs.msg.Point()
      if self.half_size is None:
        self.half_size = ufomap_msgs.msg.Point()
      if self.rotation is None:
        self.rotation = ufomap_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 72
      (_x.center.x, _x.center.y, _x.center.z, _x.half_size.x, _x.half_size.y, _x.half_size.z, _x.rotation.x, _x.rotation.y, _x.rotation.z,) = _get_struct_9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9d = None
def _get_struct_9d():
    global _struct_9d
    if _struct_9d is None:
        _struct_9d = struct.Struct("<9d")
    return _struct_9d
