// Generated by gencpp from file visualization_tools/ExploredVolumeTravedDist.msg
// DO NOT EDIT!


#ifndef VISUALIZATION_TOOLS_MESSAGE_EXPLOREDVOLUMETRAVEDDIST_H
#define VISUALIZATION_TOOLS_MESSAGE_EXPLOREDVOLUMETRAVEDDIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace visualization_tools
{
template <class ContainerAllocator>
struct ExploredVolumeTravedDist_
{
  typedef ExploredVolumeTravedDist_<ContainerAllocator> Type;

  ExploredVolumeTravedDist_()
    : header()
    , exploredVolume(0.0)
    , travedDist(0.0)  {
    }
  ExploredVolumeTravedDist_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , exploredVolume(0.0)
    , travedDist(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _exploredVolume_type;
  _exploredVolume_type exploredVolume;

   typedef double _travedDist_type;
  _travedDist_type travedDist;





  typedef boost::shared_ptr< ::visualization_tools::ExploredVolumeTravedDist_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::visualization_tools::ExploredVolumeTravedDist_<ContainerAllocator> const> ConstPtr;

}; // struct ExploredVolumeTravedDist_

typedef ::visualization_tools::ExploredVolumeTravedDist_<std::allocator<void> > ExploredVolumeTravedDist;

typedef boost::shared_ptr< ::visualization_tools::ExploredVolumeTravedDist > ExploredVolumeTravedDistPtr;
typedef boost::shared_ptr< ::visualization_tools::ExploredVolumeTravedDist const> ExploredVolumeTravedDistConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::visualization_tools::ExploredVolumeTravedDist_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::visualization_tools::ExploredVolumeTravedDist_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::visualization_tools::ExploredVolumeTravedDist_<ContainerAllocator1> & lhs, const ::visualization_tools::ExploredVolumeTravedDist_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.exploredVolume == rhs.exploredVolume &&
    lhs.travedDist == rhs.travedDist;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::visualization_tools::ExploredVolumeTravedDist_<ContainerAllocator1> & lhs, const ::visualization_tools::ExploredVolumeTravedDist_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace visualization_tools

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::visualization_tools::ExploredVolumeTravedDist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visualization_tools::ExploredVolumeTravedDist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visualization_tools::ExploredVolumeTravedDist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visualization_tools::ExploredVolumeTravedDist_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visualization_tools::ExploredVolumeTravedDist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visualization_tools::ExploredVolumeTravedDist_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::visualization_tools::ExploredVolumeTravedDist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e0c06bd8d6539e3eda299d9dcba041e2";
  }

  static const char* value(const ::visualization_tools::ExploredVolumeTravedDist_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe0c06bd8d6539e3eULL;
  static const uint64_t static_value2 = 0xda299d9dcba041e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::visualization_tools::ExploredVolumeTravedDist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "visualization_tools/ExploredVolumeTravedDist";
  }

  static const char* value(const ::visualization_tools::ExploredVolumeTravedDist_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::visualization_tools::ExploredVolumeTravedDist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"Header header\n"
"float64 exploredVolume\n"
"float64 travedDist\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::visualization_tools::ExploredVolumeTravedDist_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::visualization_tools::ExploredVolumeTravedDist_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.exploredVolume);
      stream.next(m.travedDist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExploredVolumeTravedDist_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::visualization_tools::ExploredVolumeTravedDist_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::visualization_tools::ExploredVolumeTravedDist_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "exploredVolume: ";
    Printer<double>::stream(s, indent + "  ", v.exploredVolume);
    s << indent << "travedDist: ";
    Printer<double>::stream(s, indent + "  ", v.travedDist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISUALIZATION_TOOLS_MESSAGE_EXPLOREDVOLUMETRAVEDDIST_H
