// Generated by gencpp from file visualization_tools/ViewpointGain.msg
// DO NOT EDIT!


#ifndef VISUALIZATION_TOOLS_MESSAGE_VIEWPOINTGAIN_H
#define VISUALIZATION_TOOLS_MESSAGE_VIEWPOINTGAIN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace visualization_tools
{
template <class ContainerAllocator>
struct ViewpointGain_
{
  typedef ViewpointGain_<ContainerAllocator> Type;

  ViewpointGain_()
    : header()
    , viewpoints_ids()
    , frontiers_gains()
    , unmapped_gains()  {
    }
  ViewpointGain_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , viewpoints_ids(_alloc)
    , frontiers_gains(_alloc)
    , unmapped_gains(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _viewpoints_ids_type;
  _viewpoints_ids_type viewpoints_ids;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _frontiers_gains_type;
  _frontiers_gains_type frontiers_gains;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _unmapped_gains_type;
  _unmapped_gains_type unmapped_gains;





  typedef boost::shared_ptr< ::visualization_tools::ViewpointGain_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::visualization_tools::ViewpointGain_<ContainerAllocator> const> ConstPtr;

}; // struct ViewpointGain_

typedef ::visualization_tools::ViewpointGain_<std::allocator<void> > ViewpointGain;

typedef boost::shared_ptr< ::visualization_tools::ViewpointGain > ViewpointGainPtr;
typedef boost::shared_ptr< ::visualization_tools::ViewpointGain const> ViewpointGainConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::visualization_tools::ViewpointGain_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::visualization_tools::ViewpointGain_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::visualization_tools::ViewpointGain_<ContainerAllocator1> & lhs, const ::visualization_tools::ViewpointGain_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.viewpoints_ids == rhs.viewpoints_ids &&
    lhs.frontiers_gains == rhs.frontiers_gains &&
    lhs.unmapped_gains == rhs.unmapped_gains;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::visualization_tools::ViewpointGain_<ContainerAllocator1> & lhs, const ::visualization_tools::ViewpointGain_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace visualization_tools

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::visualization_tools::ViewpointGain_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visualization_tools::ViewpointGain_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visualization_tools::ViewpointGain_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visualization_tools::ViewpointGain_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visualization_tools::ViewpointGain_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visualization_tools::ViewpointGain_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::visualization_tools::ViewpointGain_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0a86d71165359171b73a9d35ab987e6f";
  }

  static const char* value(const ::visualization_tools::ViewpointGain_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0a86d71165359171ULL;
  static const uint64_t static_value2 = 0xb73a9d35ab987e6fULL;
};

template<class ContainerAllocator>
struct DataType< ::visualization_tools::ViewpointGain_<ContainerAllocator> >
{
  static const char* value()
  {
    return "visualization_tools/ViewpointGain";
  }

  static const char* value(const ::visualization_tools::ViewpointGain_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::visualization_tools::ViewpointGain_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32[] viewpoints_ids\n"
"float64[] frontiers_gains\n"
"float64[] unmapped_gains\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::visualization_tools::ViewpointGain_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::visualization_tools::ViewpointGain_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.viewpoints_ids);
      stream.next(m.frontiers_gains);
      stream.next(m.unmapped_gains);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ViewpointGain_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::visualization_tools::ViewpointGain_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::visualization_tools::ViewpointGain_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "viewpoints_ids[]" << std::endl;
    for (size_t i = 0; i < v.viewpoints_ids.size(); ++i)
    {
      s << indent << "  viewpoints_ids[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.viewpoints_ids[i]);
    }
    s << indent << "frontiers_gains[]" << std::endl;
    for (size_t i = 0; i < v.frontiers_gains.size(); ++i)
    {
      s << indent << "  frontiers_gains[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.frontiers_gains[i]);
    }
    s << indent << "unmapped_gains[]" << std::endl;
    for (size_t i = 0; i < v.unmapped_gains.size(); ++i)
    {
      s << indent << "  unmapped_gains[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.unmapped_gains[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISUALIZATION_TOOLS_MESSAGE_VIEWPOINTGAIN_H
