// Generated by gencpp from file planner/PreprocessMsgs.msg
// DO NOT EDIT!


#ifndef PLANNER_MESSAGE_PREPROCESSMSGS_H
#define PLANNER_MESSAGE_PREPROCESSMSGS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ufomap_manager/UfomapWithFrontiers.h>
#include <planner/ViewpointsWithFrontiers.h>
#include <planner/RoadMapMsg.h>

namespace planner
{
template <class ContainerAllocator>
struct PreprocessMsgs_
{
  typedef PreprocessMsgs_<ContainerAllocator> Type;

  PreprocessMsgs_()
    : header()
    , ufomap_with_frontiers()
    , viewpoint_frontiers_set()
    , road_map_msg()  {
    }
  PreprocessMsgs_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ufomap_with_frontiers(_alloc)
    , viewpoint_frontiers_set(_alloc)
    , road_map_msg(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::ufomap_manager::UfomapWithFrontiers_<ContainerAllocator>  _ufomap_with_frontiers_type;
  _ufomap_with_frontiers_type ufomap_with_frontiers;

   typedef std::vector< ::planner::ViewpointsWithFrontiers_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::planner::ViewpointsWithFrontiers_<ContainerAllocator> >> _viewpoint_frontiers_set_type;
  _viewpoint_frontiers_set_type viewpoint_frontiers_set;

   typedef  ::planner::RoadMapMsg_<ContainerAllocator>  _road_map_msg_type;
  _road_map_msg_type road_map_msg;





  typedef boost::shared_ptr< ::planner::PreprocessMsgs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner::PreprocessMsgs_<ContainerAllocator> const> ConstPtr;

}; // struct PreprocessMsgs_

typedef ::planner::PreprocessMsgs_<std::allocator<void> > PreprocessMsgs;

typedef boost::shared_ptr< ::planner::PreprocessMsgs > PreprocessMsgsPtr;
typedef boost::shared_ptr< ::planner::PreprocessMsgs const> PreprocessMsgsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner::PreprocessMsgs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner::PreprocessMsgs_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::planner::PreprocessMsgs_<ContainerAllocator1> & lhs, const ::planner::PreprocessMsgs_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ufomap_with_frontiers == rhs.ufomap_with_frontiers &&
    lhs.viewpoint_frontiers_set == rhs.viewpoint_frontiers_set &&
    lhs.road_map_msg == rhs.road_map_msg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::planner::PreprocessMsgs_<ContainerAllocator1> & lhs, const ::planner::PreprocessMsgs_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::planner::PreprocessMsgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner::PreprocessMsgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner::PreprocessMsgs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner::PreprocessMsgs_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner::PreprocessMsgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner::PreprocessMsgs_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner::PreprocessMsgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73bcf5cb2848fb40ea7e49ae1282eac0";
  }

  static const char* value(const ::planner::PreprocessMsgs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73bcf5cb2848fb40ULL;
  static const uint64_t static_value2 = 0xea7e49ae1282eac0ULL;
};

template<class ContainerAllocator>
struct DataType< ::planner::PreprocessMsgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner/PreprocessMsgs";
  }

  static const char* value(const ::planner::PreprocessMsgs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner::PreprocessMsgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"Header header\n"
"\n"
"ufomap_manager/UfomapWithFrontiers ufomap_with_frontiers\n"
"\n"
"ViewpointsWithFrontiers[] viewpoint_frontiers_set\n"
"\n"
"RoadMapMsg road_map_msg\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ufomap_manager/UfomapWithFrontiers\n"
"Header header\n"
"\n"
"ufomap_msgs/UFOMap  ufomap\n"
"\n"
"#geometry_msgs/Point[] local_frontiers_center\n"
"#geometry_msgs/Point[] global_frontiers_center\n"
"#\n"
"#int32 frontiers_depth\n"
"\n"
"ufomap_manager/CellCode[] local_frontiers\n"
"ufomap_manager/CellCode[] global_frontiers\n"
"ufomap_manager/CellCode[] changed_cell_codes\n"
"ufomap_manager/CellCode[] known_cell_codes\n"
"\n"
"# 构建ufomap时机器人的参数配置\n"
"string frame_id\n"
"string robot_base_frame_id\n"
"float64 robot_height\n"
"float64 robot_bottom\n"
"float64 robot_radius\n"
"float64 max_range\n"
"\n"
"uint32 known_plane_cell_num\n"
"================================================================================\n"
"MSG: ufomap_msgs/UFOMap\n"
"# A 3D map in binary format, as Octree\n"
"ufomap_msgs/UFOMapMetaData info\n"
"\n"
"# Binary serialization of Octree, use conversions.h to read and write octrees\n"
"int8[] data\n"
"================================================================================\n"
"MSG: ufomap_msgs/UFOMapMetaData\n"
"# File version used\n"
"string version\n"
"\n"
"# Class id of the contained Octree\n"
"string id\n"
"\n"
"# Resolution (in m) of the octree leaf nodes\n"
"float64 resolution\n"
"\n"
"# Number of depth levels\n"
"uint8 depth_levels\n"
"\n"
"# If data is compressed\n"
"bool compressed\n"
"\n"
"# Size of data uncompressed\n"
"int32 uncompressed_data_size\n"
"\n"
"# Bounding volume\n"
"ufomap_msgs/BoundingVolume bounding_volume\n"
"================================================================================\n"
"MSG: ufomap_msgs/BoundingVolume\n"
"ufomap_msgs/AABB[] aabbs\n"
"\n"
"# ufomap_msgs/Capsule[] capsules\n"
"\n"
"# ufomap_msgs/Cone[] cones\n"
"\n"
"# ufomap_msgs/Cylinder[] cylinders\n"
"\n"
"# ufomap_msgs/Ellipsoid[] ellipsoids\n"
"\n"
"ufomap_msgs/Frustum[] frustums\n"
"\n"
"ufomap_msgs/LineSegment[] line_segments\n"
"\n"
"ufomap_msgs/OBB[] obbs\n"
"\n"
"ufomap_msgs/Plane[] planes\n"
"\n"
"ufomap_msgs/Point[] points\n"
"\n"
"ufomap_msgs/Ray[] rays\n"
"\n"
"ufomap_msgs/Sphere[] spheres\n"
"\n"
"# ufomap_msgs/Triangle[] triangles\n"
"================================================================================\n"
"MSG: ufomap_msgs/AABB\n"
"ufomap_msgs/Point center\n"
"\n"
"ufomap_msgs/Point half_size\n"
"================================================================================\n"
"MSG: ufomap_msgs/Point\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: ufomap_msgs/Frustum\n"
"ufomap_msgs/Plane[6] planes\n"
"================================================================================\n"
"MSG: ufomap_msgs/Plane\n"
"ufomap_msgs/Point normal\n"
"\n"
"float64 distance\n"
"================================================================================\n"
"MSG: ufomap_msgs/LineSegment\n"
"ufomap_msgs/Point start\n"
"\n"
"ufomap_msgs/Point end\n"
"================================================================================\n"
"MSG: ufomap_msgs/OBB\n"
"ufomap_msgs/Point center\n"
"\n"
"ufomap_msgs/Point half_size\n"
"\n"
"ufomap_msgs/Point rotation\n"
"================================================================================\n"
"MSG: ufomap_msgs/Ray\n"
"ufomap_msgs/Point origin\n"
"\n"
"ufomap_msgs/Point direction\n"
"================================================================================\n"
"MSG: ufomap_msgs/Sphere\n"
"ufomap_msgs/Point center\n"
"\n"
"float64 radius\n"
"================================================================================\n"
"MSG: ufomap_manager/CellCode\n"
"uint32 depth\n"
"uint64 Code\n"
"\n"
"================================================================================\n"
"MSG: planner/ViewpointsWithFrontiers\n"
"\n"
"geometry_msgs/Point view_point\n"
"ufomap_manager/CellCode[] frontiers\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: planner/RoadMapMsg\n"
"\n"
"IdPointPair[] id_point_pair_list\n"
"EdgePair[] edge_pair_list\n"
"================================================================================\n"
"MSG: planner/IdPointPair\n"
"int32 id\n"
"geometry_msgs/Point point\n"
"================================================================================\n"
"MSG: planner/EdgePair\n"
"\n"
"int32 edge_id\n"
"IdPointPair begin_point\n"
"IdPointPair end_point\n"
;
  }

  static const char* value(const ::planner::PreprocessMsgs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner::PreprocessMsgs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ufomap_with_frontiers);
      stream.next(m.viewpoint_frontiers_set);
      stream.next(m.road_map_msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PreprocessMsgs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner::PreprocessMsgs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner::PreprocessMsgs_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ufomap_with_frontiers: ";
    s << std::endl;
    Printer< ::ufomap_manager::UfomapWithFrontiers_<ContainerAllocator> >::stream(s, indent + "  ", v.ufomap_with_frontiers);
    s << indent << "viewpoint_frontiers_set[]" << std::endl;
    for (size_t i = 0; i < v.viewpoint_frontiers_set.size(); ++i)
    {
      s << indent << "  viewpoint_frontiers_set[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::planner::ViewpointsWithFrontiers_<ContainerAllocator> >::stream(s, indent + "    ", v.viewpoint_frontiers_set[i]);
    }
    s << indent << "road_map_msg: ";
    s << std::endl;
    Printer< ::planner::RoadMapMsg_<ContainerAllocator> >::stream(s, indent + "  ", v.road_map_msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_MESSAGE_PREPROCESSMSGS_H
