; Auto-generated. Do not edit!


(cl:in-package ufomap_msgs-msg)


;//! \htmlinclude BoundingVolume.msg.html

(cl:defclass <BoundingVolume> (roslisp-msg-protocol:ros-message)
  ((aabbs
    :reader aabbs
    :initarg :aabbs
    :type (cl:vector ufomap_msgs-msg:AABB)
   :initform (cl:make-array 0 :element-type 'ufomap_msgs-msg:AABB :initial-element (cl:make-instance 'ufomap_msgs-msg:AABB)))
   (frustums
    :reader frustums
    :initarg :frustums
    :type (cl:vector ufomap_msgs-msg:Frustum)
   :initform (cl:make-array 0 :element-type 'ufomap_msgs-msg:Frustum :initial-element (cl:make-instance 'ufomap_msgs-msg:Frustum)))
   (line_segments
    :reader line_segments
    :initarg :line_segments
    :type (cl:vector ufomap_msgs-msg:LineSegment)
   :initform (cl:make-array 0 :element-type 'ufomap_msgs-msg:LineSegment :initial-element (cl:make-instance 'ufomap_msgs-msg:LineSegment)))
   (obbs
    :reader obbs
    :initarg :obbs
    :type (cl:vector ufomap_msgs-msg:OBB)
   :initform (cl:make-array 0 :element-type 'ufomap_msgs-msg:OBB :initial-element (cl:make-instance 'ufomap_msgs-msg:OBB)))
   (planes
    :reader planes
    :initarg :planes
    :type (cl:vector ufomap_msgs-msg:Plane)
   :initform (cl:make-array 0 :element-type 'ufomap_msgs-msg:Plane :initial-element (cl:make-instance 'ufomap_msgs-msg:Plane)))
   (points
    :reader points
    :initarg :points
    :type (cl:vector ufomap_msgs-msg:Point)
   :initform (cl:make-array 0 :element-type 'ufomap_msgs-msg:Point :initial-element (cl:make-instance 'ufomap_msgs-msg:Point)))
   (rays
    :reader rays
    :initarg :rays
    :type (cl:vector ufomap_msgs-msg:Ray)
   :initform (cl:make-array 0 :element-type 'ufomap_msgs-msg:Ray :initial-element (cl:make-instance 'ufomap_msgs-msg:Ray)))
   (spheres
    :reader spheres
    :initarg :spheres
    :type (cl:vector ufomap_msgs-msg:Sphere)
   :initform (cl:make-array 0 :element-type 'ufomap_msgs-msg:Sphere :initial-element (cl:make-instance 'ufomap_msgs-msg:Sphere))))
)

(cl:defclass BoundingVolume (<BoundingVolume>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <BoundingVolume>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'BoundingVolume)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ufomap_msgs-msg:<BoundingVolume> is deprecated: use ufomap_msgs-msg:BoundingVolume instead.")))

(cl:ensure-generic-function 'aabbs-val :lambda-list '(m))
(cl:defmethod aabbs-val ((m <BoundingVolume>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ufomap_msgs-msg:aabbs-val is deprecated.  Use ufomap_msgs-msg:aabbs instead.")
  (aabbs m))

(cl:ensure-generic-function 'frustums-val :lambda-list '(m))
(cl:defmethod frustums-val ((m <BoundingVolume>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ufomap_msgs-msg:frustums-val is deprecated.  Use ufomap_msgs-msg:frustums instead.")
  (frustums m))

(cl:ensure-generic-function 'line_segments-val :lambda-list '(m))
(cl:defmethod line_segments-val ((m <BoundingVolume>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ufomap_msgs-msg:line_segments-val is deprecated.  Use ufomap_msgs-msg:line_segments instead.")
  (line_segments m))

(cl:ensure-generic-function 'obbs-val :lambda-list '(m))
(cl:defmethod obbs-val ((m <BoundingVolume>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ufomap_msgs-msg:obbs-val is deprecated.  Use ufomap_msgs-msg:obbs instead.")
  (obbs m))

(cl:ensure-generic-function 'planes-val :lambda-list '(m))
(cl:defmethod planes-val ((m <BoundingVolume>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ufomap_msgs-msg:planes-val is deprecated.  Use ufomap_msgs-msg:planes instead.")
  (planes m))

(cl:ensure-generic-function 'points-val :lambda-list '(m))
(cl:defmethod points-val ((m <BoundingVolume>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ufomap_msgs-msg:points-val is deprecated.  Use ufomap_msgs-msg:points instead.")
  (points m))

(cl:ensure-generic-function 'rays-val :lambda-list '(m))
(cl:defmethod rays-val ((m <BoundingVolume>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ufomap_msgs-msg:rays-val is deprecated.  Use ufomap_msgs-msg:rays instead.")
  (rays m))

(cl:ensure-generic-function 'spheres-val :lambda-list '(m))
(cl:defmethod spheres-val ((m <BoundingVolume>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ufomap_msgs-msg:spheres-val is deprecated.  Use ufomap_msgs-msg:spheres instead.")
  (spheres m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <BoundingVolume>) ostream)
  "Serializes a message object of type '<BoundingVolume>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'aabbs))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'aabbs))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'frustums))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'frustums))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'line_segments))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'line_segments))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'obbs))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'obbs))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'planes))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'planes))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'points))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'points))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'rays))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'rays))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'spheres))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'spheres))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <BoundingVolume>) istream)
  "Deserializes a message object of type '<BoundingVolume>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'aabbs) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'aabbs)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'ufomap_msgs-msg:AABB))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'frustums) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'frustums)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'ufomap_msgs-msg:Frustum))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'line_segments) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'line_segments)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'ufomap_msgs-msg:LineSegment))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'obbs) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'obbs)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'ufomap_msgs-msg:OBB))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'planes) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'planes)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'ufomap_msgs-msg:Plane))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'points) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'points)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'ufomap_msgs-msg:Point))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'rays) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'rays)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'ufomap_msgs-msg:Ray))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'spheres) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'spheres)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'ufomap_msgs-msg:Sphere))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<BoundingVolume>)))
  "Returns string type for a message object of type '<BoundingVolume>"
  "ufomap_msgs/BoundingVolume")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'BoundingVolume)))
  "Returns string type for a message object of type 'BoundingVolume"
  "ufomap_msgs/BoundingVolume")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<BoundingVolume>)))
  "Returns md5sum for a message object of type '<BoundingVolume>"
  "82212eec286e703b5b3c33cc90377d90")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'BoundingVolume)))
  "Returns md5sum for a message object of type 'BoundingVolume"
  "82212eec286e703b5b3c33cc90377d90")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<BoundingVolume>)))
  "Returns full string definition for message of type '<BoundingVolume>"
  (cl:format cl:nil "ufomap_msgs/AABB[] aabbs~%~%# ufomap_msgs/Capsule[] capsules~%~%# ufomap_msgs/Cone[] cones~%~%# ufomap_msgs/Cylinder[] cylinders~%~%# ufomap_msgs/Ellipsoid[] ellipsoids~%~%ufomap_msgs/Frustum[] frustums~%~%ufomap_msgs/LineSegment[] line_segments~%~%ufomap_msgs/OBB[] obbs~%~%ufomap_msgs/Plane[] planes~%~%ufomap_msgs/Point[] points~%~%ufomap_msgs/Ray[] rays~%~%ufomap_msgs/Sphere[] spheres~%~%# ufomap_msgs/Triangle[] triangles~%================================================================================~%MSG: ufomap_msgs/AABB~%ufomap_msgs/Point center~%~%ufomap_msgs/Point half_size~%================================================================================~%MSG: ufomap_msgs/Point~%float64 x~%float64 y~%float64 z~%================================================================================~%MSG: ufomap_msgs/Frustum~%ufomap_msgs/Plane[6] planes~%================================================================================~%MSG: ufomap_msgs/Plane~%ufomap_msgs/Point normal~%~%float64 distance~%================================================================================~%MSG: ufomap_msgs/LineSegment~%ufomap_msgs/Point start~%~%ufomap_msgs/Point end~%================================================================================~%MSG: ufomap_msgs/OBB~%ufomap_msgs/Point center~%~%ufomap_msgs/Point half_size~%~%ufomap_msgs/Point rotation~%================================================================================~%MSG: ufomap_msgs/Ray~%ufomap_msgs/Point origin~%~%ufomap_msgs/Point direction~%================================================================================~%MSG: ufomap_msgs/Sphere~%ufomap_msgs/Point center~%~%float64 radius~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'BoundingVolume)))
  "Returns full string definition for message of type 'BoundingVolume"
  (cl:format cl:nil "ufomap_msgs/AABB[] aabbs~%~%# ufomap_msgs/Capsule[] capsules~%~%# ufomap_msgs/Cone[] cones~%~%# ufomap_msgs/Cylinder[] cylinders~%~%# ufomap_msgs/Ellipsoid[] ellipsoids~%~%ufomap_msgs/Frustum[] frustums~%~%ufomap_msgs/LineSegment[] line_segments~%~%ufomap_msgs/OBB[] obbs~%~%ufomap_msgs/Plane[] planes~%~%ufomap_msgs/Point[] points~%~%ufomap_msgs/Ray[] rays~%~%ufomap_msgs/Sphere[] spheres~%~%# ufomap_msgs/Triangle[] triangles~%================================================================================~%MSG: ufomap_msgs/AABB~%ufomap_msgs/Point center~%~%ufomap_msgs/Point half_size~%================================================================================~%MSG: ufomap_msgs/Point~%float64 x~%float64 y~%float64 z~%================================================================================~%MSG: ufomap_msgs/Frustum~%ufomap_msgs/Plane[6] planes~%================================================================================~%MSG: ufomap_msgs/Plane~%ufomap_msgs/Point normal~%~%float64 distance~%================================================================================~%MSG: ufomap_msgs/LineSegment~%ufomap_msgs/Point start~%~%ufomap_msgs/Point end~%================================================================================~%MSG: ufomap_msgs/OBB~%ufomap_msgs/Point center~%~%ufomap_msgs/Point half_size~%~%ufomap_msgs/Point rotation~%================================================================================~%MSG: ufomap_msgs/Ray~%ufomap_msgs/Point origin~%~%ufomap_msgs/Point direction~%================================================================================~%MSG: ufomap_msgs/Sphere~%ufomap_msgs/Point center~%~%float64 radius~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <BoundingVolume>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'aabbs) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'frustums) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'line_segments) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'obbs) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'planes) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'points) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'rays) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'spheres) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <BoundingVolume>))
  "Converts a ROS message object to a list"
  (cl:list 'BoundingVolume
    (cl:cons ':aabbs (aabbs msg))
    (cl:cons ':frustums (frustums msg))
    (cl:cons ':line_segments (line_segments msg))
    (cl:cons ':obbs (obbs msg))
    (cl:cons ':planes (planes msg))
    (cl:cons ':points (points msg))
    (cl:cons ':rays (rays msg))
    (cl:cons ':spheres (spheres msg))
))
