// Generated by gencpp from file ufomap_msgs/LineSegment.msg
// DO NOT EDIT!


#ifndef UFOMAP_MSGS_MESSAGE_LINESEGMENT_H
#define UFOMAP_MSGS_MESSAGE_LINESEGMENT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ufomap_msgs/Point.h>
#include <ufomap_msgs/Point.h>

namespace ufomap_msgs
{
template <class ContainerAllocator>
struct LineSegment_
{
  typedef LineSegment_<ContainerAllocator> Type;

  LineSegment_()
    : start()
    , end()  {
    }
  LineSegment_(const ContainerAllocator& _alloc)
    : start(_alloc)
    , end(_alloc)  {
  (void)_alloc;
    }



   typedef  ::ufomap_msgs::Point_<ContainerAllocator>  _start_type;
  _start_type start;

   typedef  ::ufomap_msgs::Point_<ContainerAllocator>  _end_type;
  _end_type end;





  typedef boost::shared_ptr< ::ufomap_msgs::LineSegment_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ufomap_msgs::LineSegment_<ContainerAllocator> const> ConstPtr;

}; // struct LineSegment_

typedef ::ufomap_msgs::LineSegment_<std::allocator<void> > LineSegment;

typedef boost::shared_ptr< ::ufomap_msgs::LineSegment > LineSegmentPtr;
typedef boost::shared_ptr< ::ufomap_msgs::LineSegment const> LineSegmentConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ufomap_msgs::LineSegment_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ufomap_msgs::LineSegment_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ufomap_msgs::LineSegment_<ContainerAllocator1> & lhs, const ::ufomap_msgs::LineSegment_<ContainerAllocator2> & rhs)
{
  return lhs.start == rhs.start &&
    lhs.end == rhs.end;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ufomap_msgs::LineSegment_<ContainerAllocator1> & lhs, const ::ufomap_msgs::LineSegment_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ufomap_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ufomap_msgs::LineSegment_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ufomap_msgs::LineSegment_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ufomap_msgs::LineSegment_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ufomap_msgs::LineSegment_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ufomap_msgs::LineSegment_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ufomap_msgs::LineSegment_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ufomap_msgs::LineSegment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad6f4eea34a193d38008f1d4053cce66";
  }

  static const char* value(const ::ufomap_msgs::LineSegment_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad6f4eea34a193d3ULL;
  static const uint64_t static_value2 = 0x8008f1d4053cce66ULL;
};

template<class ContainerAllocator>
struct DataType< ::ufomap_msgs::LineSegment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ufomap_msgs/LineSegment";
  }

  static const char* value(const ::ufomap_msgs::LineSegment_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ufomap_msgs::LineSegment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ufomap_msgs/Point start\n"
"\n"
"ufomap_msgs/Point end\n"
"================================================================================\n"
"MSG: ufomap_msgs/Point\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::ufomap_msgs::LineSegment_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ufomap_msgs::LineSegment_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
      stream.next(m.end);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LineSegment_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ufomap_msgs::LineSegment_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ufomap_msgs::LineSegment_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    s << std::endl;
    Printer< ::ufomap_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.start);
    s << indent << "end: ";
    s << std::endl;
    Printer< ::ufomap_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.end);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UFOMAP_MSGS_MESSAGE_LINESEGMENT_H
