// Generated by gencpp from file ufomap_msgs/Ray.msg
// DO NOT EDIT!


#ifndef UFOMAP_MSGS_MESSAGE_RAY_H
#define UFOMAP_MSGS_MESSAGE_RAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ufomap_msgs/Point.h>
#include <ufomap_msgs/Point.h>

namespace ufomap_msgs
{
template <class ContainerAllocator>
struct Ray_
{
  typedef Ray_<ContainerAllocator> Type;

  Ray_()
    : origin()
    , direction()  {
    }
  Ray_(const ContainerAllocator& _alloc)
    : origin(_alloc)
    , direction(_alloc)  {
  (void)_alloc;
    }



   typedef  ::ufomap_msgs::Point_<ContainerAllocator>  _origin_type;
  _origin_type origin;

   typedef  ::ufomap_msgs::Point_<ContainerAllocator>  _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::ufomap_msgs::Ray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ufomap_msgs::Ray_<ContainerAllocator> const> ConstPtr;

}; // struct Ray_

typedef ::ufomap_msgs::Ray_<std::allocator<void> > Ray;

typedef boost::shared_ptr< ::ufomap_msgs::Ray > RayPtr;
typedef boost::shared_ptr< ::ufomap_msgs::Ray const> RayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ufomap_msgs::Ray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ufomap_msgs::Ray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ufomap_msgs::Ray_<ContainerAllocator1> & lhs, const ::ufomap_msgs::Ray_<ContainerAllocator2> & rhs)
{
  return lhs.origin == rhs.origin &&
    lhs.direction == rhs.direction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ufomap_msgs::Ray_<ContainerAllocator1> & lhs, const ::ufomap_msgs::Ray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ufomap_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ufomap_msgs::Ray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ufomap_msgs::Ray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ufomap_msgs::Ray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ufomap_msgs::Ray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ufomap_msgs::Ray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ufomap_msgs::Ray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ufomap_msgs::Ray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "872bd28a8ce427a470e8f663e7effa11";
  }

  static const char* value(const ::ufomap_msgs::Ray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x872bd28a8ce427a4ULL;
  static const uint64_t static_value2 = 0x70e8f663e7effa11ULL;
};

template<class ContainerAllocator>
struct DataType< ::ufomap_msgs::Ray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ufomap_msgs/Ray";
  }

  static const char* value(const ::ufomap_msgs::Ray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ufomap_msgs::Ray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ufomap_msgs/Point origin\n"
"\n"
"ufomap_msgs/Point direction\n"
"================================================================================\n"
"MSG: ufomap_msgs/Point\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::ufomap_msgs::Ray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ufomap_msgs::Ray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.origin);
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ufomap_msgs::Ray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ufomap_msgs::Ray_<ContainerAllocator>& v)
  {
    s << indent << "origin: ";
    s << std::endl;
    Printer< ::ufomap_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.origin);
    s << indent << "direction: ";
    s << std::endl;
    Printer< ::ufomap_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UFOMAP_MSGS_MESSAGE_RAY_H
