// Generated by gencpp from file ufomap_msgs/Sphere.msg
// DO NOT EDIT!


#ifndef UFOMAP_MSGS_MESSAGE_SPHERE_H
#define UFOMAP_MSGS_MESSAGE_SPHERE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ufomap_msgs/Point.h>

namespace ufomap_msgs
{
template <class ContainerAllocator>
struct Sphere_
{
  typedef Sphere_<ContainerAllocator> Type;

  Sphere_()
    : center()
    , radius(0.0)  {
    }
  Sphere_(const ContainerAllocator& _alloc)
    : center(_alloc)
    , radius(0.0)  {
  (void)_alloc;
    }



   typedef  ::ufomap_msgs::Point_<ContainerAllocator>  _center_type;
  _center_type center;

   typedef double _radius_type;
  _radius_type radius;





  typedef boost::shared_ptr< ::ufomap_msgs::Sphere_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ufomap_msgs::Sphere_<ContainerAllocator> const> ConstPtr;

}; // struct Sphere_

typedef ::ufomap_msgs::Sphere_<std::allocator<void> > Sphere;

typedef boost::shared_ptr< ::ufomap_msgs::Sphere > SpherePtr;
typedef boost::shared_ptr< ::ufomap_msgs::Sphere const> SphereConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ufomap_msgs::Sphere_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ufomap_msgs::Sphere_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ufomap_msgs::Sphere_<ContainerAllocator1> & lhs, const ::ufomap_msgs::Sphere_<ContainerAllocator2> & rhs)
{
  return lhs.center == rhs.center &&
    lhs.radius == rhs.radius;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ufomap_msgs::Sphere_<ContainerAllocator1> & lhs, const ::ufomap_msgs::Sphere_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ufomap_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ufomap_msgs::Sphere_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ufomap_msgs::Sphere_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ufomap_msgs::Sphere_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ufomap_msgs::Sphere_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ufomap_msgs::Sphere_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ufomap_msgs::Sphere_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ufomap_msgs::Sphere_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ab296cd39c1a1fa7dd67209d6a4767e1";
  }

  static const char* value(const ::ufomap_msgs::Sphere_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xab296cd39c1a1fa7ULL;
  static const uint64_t static_value2 = 0xdd67209d6a4767e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::ufomap_msgs::Sphere_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ufomap_msgs/Sphere";
  }

  static const char* value(const ::ufomap_msgs::Sphere_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ufomap_msgs::Sphere_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ufomap_msgs/Point center\n"
"\n"
"float64 radius\n"
"================================================================================\n"
"MSG: ufomap_msgs/Point\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::ufomap_msgs::Sphere_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ufomap_msgs::Sphere_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.center);
      stream.next(m.radius);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Sphere_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ufomap_msgs::Sphere_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ufomap_msgs::Sphere_<ContainerAllocator>& v)
  {
    s << indent << "center: ";
    s << std::endl;
    Printer< ::ufomap_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.center);
    s << indent << "radius: ";
    Printer<double>::stream(s, indent + "  ", v.radius);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UFOMAP_MSGS_MESSAGE_SPHERE_H
