(cl:defpackage ufomap_srvs-srv
  (:use )
  (:export
   "CLEARVOLUME"
   "<CLEARVOLUME-REQUEST>"
   "CLEARVOLUME-REQUEST"
   "<CLEARVOLUME-RESPONSE>"
   "CLEARVOLUME-RESPONSE"
   "GETMAP"
   "<GETMAP-REQUEST>"
   "GETMAP-REQUEST"
   "<GETMAP-RESPONSE>"
   "GETMAP-RESPONSE"
   "RESET"
   "<RESET-REQUEST>"
   "RESET-REQUEST"
   "<RESET-RESPONSE>"
   "RESET-RESPONSE"
   "SAVEMAP"
   "<SAVEMAP-REQUEST>"
   "SAVEMAP-REQUEST"
   "<SAVEMAP-RESPONSE>"
   "SAVEMAP-RESPONSE"
  ))

