// Generated by gencpp from file ufomap_srvs/ClearVolume.msg
// DO NOT EDIT!


#ifndef UFOMAP_SRVS_MESSAGE_CLEARVOLUME_H
#define UFOMAP_SRVS_MESSAGE_CLEARVOLUME_H

#include <ros/service_traits.h>


#include <ufomap_srvs/ClearVolumeRequest.h>
#include <ufomap_srvs/ClearVolumeResponse.h>


namespace ufomap_srvs
{

struct ClearVolume
{

typedef ClearVolumeRequest Request;
typedef ClearVolumeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClearVolume
} // namespace ufomap_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ufomap_srvs::ClearVolume > {
  static const char* value()
  {
    return "d2fd0d5791e4eff60d2c257423ccf8ba";
  }

  static const char* value(const ::ufomap_srvs::ClearVolume&) { return value(); }
};

template<>
struct DataType< ::ufomap_srvs::ClearVolume > {
  static const char* value()
  {
    return "ufomap_srvs/ClearVolume";
  }

  static const char* value(const ::ufomap_srvs::ClearVolume&) { return value(); }
};


// service_traits::MD5Sum< ::ufomap_srvs::ClearVolumeRequest> should match
// service_traits::MD5Sum< ::ufomap_srvs::ClearVolume >
template<>
struct MD5Sum< ::ufomap_srvs::ClearVolumeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ufomap_srvs::ClearVolume >::value();
  }
  static const char* value(const ::ufomap_srvs::ClearVolumeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ufomap_srvs::ClearVolumeRequest> should match
// service_traits::DataType< ::ufomap_srvs::ClearVolume >
template<>
struct DataType< ::ufomap_srvs::ClearVolumeRequest>
{
  static const char* value()
  {
    return DataType< ::ufomap_srvs::ClearVolume >::value();
  }
  static const char* value(const ::ufomap_srvs::ClearVolumeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ufomap_srvs::ClearVolumeResponse> should match
// service_traits::MD5Sum< ::ufomap_srvs::ClearVolume >
template<>
struct MD5Sum< ::ufomap_srvs::ClearVolumeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ufomap_srvs::ClearVolume >::value();
  }
  static const char* value(const ::ufomap_srvs::ClearVolumeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ufomap_srvs::ClearVolumeResponse> should match
// service_traits::DataType< ::ufomap_srvs::ClearVolume >
template<>
struct DataType< ::ufomap_srvs::ClearVolumeResponse>
{
  static const char* value()
  {
    return DataType< ::ufomap_srvs::ClearVolume >::value();
  }
  static const char* value(const ::ufomap_srvs::ClearVolumeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UFOMAP_SRVS_MESSAGE_CLEARVOLUME_H
