// Generated by gencpp from file ufomap_srvs/SaveMapRequest.msg
// DO NOT EDIT!


#ifndef UFOMAP_SRVS_MESSAGE_SAVEMAPREQUEST_H
#define UFOMAP_SRVS_MESSAGE_SAVEMAPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ufomap_msgs/BoundingVolume.h>

namespace ufomap_srvs
{
template <class ContainerAllocator>
struct SaveMapRequest_
{
  typedef SaveMapRequest_<ContainerAllocator> Type;

  SaveMapRequest_()
    : filename()
    , depth(0)
    , compress(false)
    , compression_level(0)
    , bounding_volume()  {
    }
  SaveMapRequest_(const ContainerAllocator& _alloc)
    : filename(_alloc)
    , depth(0)
    , compress(false)
    , compression_level(0)
    , bounding_volume(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _filename_type;
  _filename_type filename;

   typedef uint8_t _depth_type;
  _depth_type depth;

   typedef uint8_t _compress_type;
  _compress_type compress;

   typedef int32_t _compression_level_type;
  _compression_level_type compression_level;

   typedef  ::ufomap_msgs::BoundingVolume_<ContainerAllocator>  _bounding_volume_type;
  _bounding_volume_type bounding_volume;





  typedef boost::shared_ptr< ::ufomap_srvs::SaveMapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ufomap_srvs::SaveMapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SaveMapRequest_

typedef ::ufomap_srvs::SaveMapRequest_<std::allocator<void> > SaveMapRequest;

typedef boost::shared_ptr< ::ufomap_srvs::SaveMapRequest > SaveMapRequestPtr;
typedef boost::shared_ptr< ::ufomap_srvs::SaveMapRequest const> SaveMapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ufomap_srvs::SaveMapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ufomap_srvs::SaveMapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ufomap_srvs::SaveMapRequest_<ContainerAllocator1> & lhs, const ::ufomap_srvs::SaveMapRequest_<ContainerAllocator2> & rhs)
{
  return lhs.filename == rhs.filename &&
    lhs.depth == rhs.depth &&
    lhs.compress == rhs.compress &&
    lhs.compression_level == rhs.compression_level &&
    lhs.bounding_volume == rhs.bounding_volume;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ufomap_srvs::SaveMapRequest_<ContainerAllocator1> & lhs, const ::ufomap_srvs::SaveMapRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ufomap_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ufomap_srvs::SaveMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ufomap_srvs::SaveMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ufomap_srvs::SaveMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ufomap_srvs::SaveMapRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ufomap_srvs::SaveMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ufomap_srvs::SaveMapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ufomap_srvs::SaveMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9640eaf6c56407ea04c1bba1685c8ded";
  }

  static const char* value(const ::ufomap_srvs::SaveMapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9640eaf6c56407eaULL;
  static const uint64_t static_value2 = 0x04c1bba1685c8dedULL;
};

template<class ContainerAllocator>
struct DataType< ::ufomap_srvs::SaveMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ufomap_srvs/SaveMapRequest";
  }

  static const char* value(const ::ufomap_srvs::SaveMapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ufomap_srvs::SaveMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Save the map to file\n"
"\n"
"# Name of the file\n"
"string filename\n"
"# The depth of the map to save\n"
"uint8 depth\n"
"# If the file should be compressed\n"
"bool compress\n"
"# Compression level (higher number equals more compressed)\n"
"int32 compression_level\n"
"# Bounding volume of which part of the map should be saved\n"
"ufomap_msgs/BoundingVolume bounding_volume\n"
"\n"
"================================================================================\n"
"MSG: ufomap_msgs/BoundingVolume\n"
"ufomap_msgs/AABB[] aabbs\n"
"\n"
"# ufomap_msgs/Capsule[] capsules\n"
"\n"
"# ufomap_msgs/Cone[] cones\n"
"\n"
"# ufomap_msgs/Cylinder[] cylinders\n"
"\n"
"# ufomap_msgs/Ellipsoid[] ellipsoids\n"
"\n"
"ufomap_msgs/Frustum[] frustums\n"
"\n"
"ufomap_msgs/LineSegment[] line_segments\n"
"\n"
"ufomap_msgs/OBB[] obbs\n"
"\n"
"ufomap_msgs/Plane[] planes\n"
"\n"
"ufomap_msgs/Point[] points\n"
"\n"
"ufomap_msgs/Ray[] rays\n"
"\n"
"ufomap_msgs/Sphere[] spheres\n"
"\n"
"# ufomap_msgs/Triangle[] triangles\n"
"================================================================================\n"
"MSG: ufomap_msgs/AABB\n"
"ufomap_msgs/Point center\n"
"\n"
"ufomap_msgs/Point half_size\n"
"================================================================================\n"
"MSG: ufomap_msgs/Point\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: ufomap_msgs/Frustum\n"
"ufomap_msgs/Plane[6] planes\n"
"================================================================================\n"
"MSG: ufomap_msgs/Plane\n"
"ufomap_msgs/Point normal\n"
"\n"
"float64 distance\n"
"================================================================================\n"
"MSG: ufomap_msgs/LineSegment\n"
"ufomap_msgs/Point start\n"
"\n"
"ufomap_msgs/Point end\n"
"================================================================================\n"
"MSG: ufomap_msgs/OBB\n"
"ufomap_msgs/Point center\n"
"\n"
"ufomap_msgs/Point half_size\n"
"\n"
"ufomap_msgs/Point rotation\n"
"================================================================================\n"
"MSG: ufomap_msgs/Ray\n"
"ufomap_msgs/Point origin\n"
"\n"
"ufomap_msgs/Point direction\n"
"================================================================================\n"
"MSG: ufomap_msgs/Sphere\n"
"ufomap_msgs/Point center\n"
"\n"
"float64 radius\n"
;
  }

  static const char* value(const ::ufomap_srvs::SaveMapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ufomap_srvs::SaveMapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.filename);
      stream.next(m.depth);
      stream.next(m.compress);
      stream.next(m.compression_level);
      stream.next(m.bounding_volume);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveMapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ufomap_srvs::SaveMapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ufomap_srvs::SaveMapRequest_<ContainerAllocator>& v)
  {
    s << indent << "filename: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.filename);
    s << indent << "depth: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.depth);
    s << indent << "compress: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compress);
    s << indent << "compression_level: ";
    Printer<int32_t>::stream(s, indent + "  ", v.compression_level);
    s << indent << "bounding_volume: ";
    s << std::endl;
    Printer< ::ufomap_msgs::BoundingVolume_<ContainerAllocator> >::stream(s, indent + "  ", v.bounding_volume);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UFOMAP_SRVS_MESSAGE_SAVEMAPREQUEST_H
