// Generated by gencpp from file ufomap_srvs/SaveMap.msg
// DO NOT EDIT!


#ifndef UFOMAP_SRVS_MESSAGE_SAVEMAP_H
#define UFOMAP_SRVS_MESSAGE_SAVEMAP_H

#include <ros/service_traits.h>


#include <ufomap_srvs/SaveMapRequest.h>
#include <ufomap_srvs/SaveMapResponse.h>


namespace ufomap_srvs
{

struct SaveMap
{

typedef SaveMapRequest Request;
typedef SaveMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveMap
} // namespace ufomap_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ufomap_srvs::SaveMap > {
  static const char* value()
  {
    return "d0fd03b00c5e25ad1ec5e95dc82eecdd";
  }

  static const char* value(const ::ufomap_srvs::SaveMap&) { return value(); }
};

template<>
struct DataType< ::ufomap_srvs::SaveMap > {
  static const char* value()
  {
    return "ufomap_srvs/SaveMap";
  }

  static const char* value(const ::ufomap_srvs::SaveMap&) { return value(); }
};


// service_traits::MD5Sum< ::ufomap_srvs::SaveMapRequest> should match
// service_traits::MD5Sum< ::ufomap_srvs::SaveMap >
template<>
struct MD5Sum< ::ufomap_srvs::SaveMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ufomap_srvs::SaveMap >::value();
  }
  static const char* value(const ::ufomap_srvs::SaveMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ufomap_srvs::SaveMapRequest> should match
// service_traits::DataType< ::ufomap_srvs::SaveMap >
template<>
struct DataType< ::ufomap_srvs::SaveMapRequest>
{
  static const char* value()
  {
    return DataType< ::ufomap_srvs::SaveMap >::value();
  }
  static const char* value(const ::ufomap_srvs::SaveMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ufomap_srvs::SaveMapResponse> should match
// service_traits::MD5Sum< ::ufomap_srvs::SaveMap >
template<>
struct MD5Sum< ::ufomap_srvs::SaveMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ufomap_srvs::SaveMap >::value();
  }
  static const char* value(const ::ufomap_srvs::SaveMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ufomap_srvs::SaveMapResponse> should match
// service_traits::DataType< ::ufomap_srvs::SaveMap >
template<>
struct DataType< ::ufomap_srvs::SaveMapResponse>
{
  static const char* value()
  {
    return DataType< ::ufomap_srvs::SaveMap >::value();
  }
  static const char* value(const ::ufomap_srvs::SaveMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UFOMAP_SRVS_MESSAGE_SAVEMAP_H
